package fleet

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/henderson-tech/vybava/internal/cmux"
	"github.com/henderson-tech/vybava/internal/runx"
)

// swiftNamed are the Go types Fleet.app decodes, in output order, with their
// Swift names. A struct referenced by a field must be listed here.
var swiftNamed = []struct {
	goType reflect.Type
	name   string
}{
	{reflect.TypeOf(runx.Diagnostic{}), "FleetDiagnostic"},
	{reflect.TypeOf(Published{}), "FleetSnapshot"},
	{reflect.TypeOf(cmux.Status{}), "CmuxStatus"},
	{reflect.TypeOf(Counts{}), "FleetCounts"},
	{reflect.TypeOf(Project{}), "FleetProject"},
	{reflect.TypeOf(Surface{}), "FleetSurface"},
	{reflect.TypeOf(Hosted{}), "FleetSession"},
	{reflect.TypeOf(HostedCodex{}), "FleetCodexSession"},
	{reflect.TypeOf(ScreenResult{}), "FleetScreen"},
	{reflect.TypeOf(Dialog{}), "FleetDialog"},
	{reflect.TypeOf(DialogTab{}), "FleetDialogTab"},
	{reflect.TypeOf(DialogOption{}), "FleetDialogOption"},
	{reflect.TypeOf(ReplyResult{}), "FleetReply"},
	{reflect.TypeOf(FocusResult{}), "FleetFocus"},
}

// swiftEnums are the string enums, rendered as String-backed Swift enums.
var swiftEnums = []struct {
	goType reflect.Type
	name   string
	values []string
}{
	{reflect.TypeOf(State("")), "FleetState", []string{string(StateWaiting), string(StateBusy), string(StateIdle), string(StateShell), string(StateDead), string(StateEnded), string(StateUnknown)}},
	{reflect.TypeOf(Liveness("")), "FleetLiveness", []string{string(LivenessAlive), string(LivenessGone), string(LivenessForeign), string(LivenessRecycled), string(LivenessUnknown)}},
	{reflect.TypeOf(Action("")), "FleetAction", []string{string(ActionFocus), string(ActionScreen), string(ActionReply)}},
	{reflect.TypeOf(DialogKind("")), "FleetDialogKind", []string{string(DialogPermission), string(DialogQuestion)}},
	{reflect.TypeOf(OptionKind("")), "FleetOptionKind", []string{string(OptionAnswer), string(OptionOther), string(OptionChat)}},
	{reflect.TypeOf(cmux.State("")), "CmuxState", []string{string(cmux.StateOK), string(cmux.StateUnreachable), string(cmux.StateDenied), string(cmux.StateRestricted), string(cmux.StateOutdated)}},
}

// swiftKeywords must be back-quoted as property names.
var swiftKeywords = map[string]bool{"default": true, "case": true, "class": true, "struct": true, "protocol": true,
	"extension": true, "import": true, "func": true, "var": true, "let": true, "in": true, "is": true, "as": true,
	"self": true, "Type": true, "where": true, "return": true, "switch": true, "enum": true, "init": true}

// swiftDateHelper decodes Go's RFC 3339 times: up to nine fractional
// digits and a numeric offset, which JSONDecoder's .iso8601 refuses.
const swiftDateHelper = `
enum FleetJSON {
    /// The decoder for snapshot.json and every fleet --json envelope.
    static func decoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .custom { decoder in
            let raw = try decoder.singleValueContainer().decode(String.self)
            guard let date = parse(raw) else {
                throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "not an RFC 3339 time: \(raw)"))
            }
            return date
        }
        return decoder
    }

    /// Parses Go's time.Time JSON; fractional seconds are cut to milliseconds.
    static func parse(_ raw: String) -> Date? {
        var text = raw
        if let dot = text.firstIndex(of: "."),
           let end = text[dot...].firstIndex(where: { $0 == "Z" || $0 == "+" || $0 == "-" }) {
            let digits = String(text[text.index(after: dot)..<end].prefix(3))
            text.replaceSubrange(dot..<end, with: "." + digits.padding(toLength: 3, withPad: "0", startingAt: 0))
        }
        if let date = try? Date.ISO8601FormatStyle(includingFractionalSeconds: true).parse(text) {
            return date
        }
        return try? Date.ISO8601FormatStyle().parse(text)
    }
}
`

// Swift renders snapshot.json's and the action verbs' contracts as one
// Swift file; Fleet.app keeps it at apps/fleet/Sources/FleetSnapshot.swift
// and its test script fails on drift from this.
func Swift() string {
	var b strings.Builder
	b.WriteString("// Code generated by `vybava fleet schema --swift`. DO NOT EDIT.\n")
	b.WriteString("// Contracts of snapshot.json and the fleet action verbs; Výbava docs/fleet.md.\n\n")
	b.WriteString("import Foundation\n\n")
	fmt.Fprintf(&b, "/// snapshot.json's version this app reads; any other is refused.\nlet fleetSnapshotVersion = %d\n", PublishedVersion)
	fmt.Fprintf(&b, "/// The runx envelope version of every `vybava fleet … --json` answer.\nlet fleetEnvelopeVersion = %d\n", runx.EnvelopeVersion)
	b.WriteString(swiftDateHelper)
	b.WriteString("\nstruct FleetEnvelope<T: Codable & Sendable & Equatable>: Codable, Sendable, Equatable {\n")
	b.WriteString("    let v: Int\n    let ok: Bool\n    let verb: String\n    let data: T?\n    let diagnostics: [FleetDiagnostic]\n    let next: [String]\n}\n")
	for _, enum := range swiftEnums {
		fmt.Fprintf(&b, "\nenum %s: String, Codable, Sendable, CaseIterable {\n", enum.name)
		for _, value := range enum.values {
			fmt.Fprintf(&b, "    case %s\n", swiftIdent(value))
		}
		b.WriteString("}\n")
	}
	for _, named := range swiftNamed {
		fmt.Fprintf(&b, "\nstruct %s: Codable, Sendable, Equatable {\n", named.name)
		swiftFields(&b, named.goType)
		b.WriteString("}\n")
	}
	return b.String()
}

// swiftFields writes a struct's properties, flattening embedded structs the
// way encoding/json does.
func swiftFields(b *strings.Builder, t reflect.Type) {
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if field.Anonymous && field.Type.Kind() == reflect.Struct && field.Tag.Get("json") == "" {
			swiftFields(b, field.Type)
			continue
		}
		name, optional, skip := jsonField(field)
		if skip {
			continue
		}
		fieldType := field.Type
		if fieldType.Kind() == reflect.Pointer {
			optional = true
			fieldType = fieldType.Elem()
		}
		mark := ""
		if optional {
			mark = "?"
		}
		fmt.Fprintf(b, "    let %s: %s%s\n", swiftIdent(name), swiftType(fieldType), mark)
	}
}

func swiftIdent(name string) string {
	if swiftKeywords[name] {
		return "`" + name + "`"
	}
	return name
}

func swiftType(t reflect.Type) string {
	if t == timeType {
		return "Date"
	}
	for _, enum := range swiftEnums {
		if t == enum.goType {
			return enum.name
		}
	}
	for _, named := range swiftNamed {
		if t == named.goType {
			return named.name
		}
	}
	switch t.Kind() {
	case reflect.String:
		return "String"
	case reflect.Bool:
		return "Bool"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "Int"
	case reflect.Float32, reflect.Float64:
		return "Double"
	case reflect.Slice, reflect.Array:
		return "[" + swiftType(t.Elem()) + "]"
	case reflect.Map:
		return "[String: " + swiftType(t.Elem()) + "]"
	case reflect.Pointer:
		return swiftType(t.Elem())
	}
	panic(fmt.Sprintf("fleet: no Swift rendering for %s — list it in swiftNamed or swiftEnums", t))
}
