package fleet

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/henderson-tech/vybava/internal/runx"
)

// tsNamed are the Go types the mods read, in output order, with their
// TypeScript names. A struct referenced by a field must be listed here.
var tsNamed = []struct {
	goType reflect.Type
	name   string
}{
	{reflect.TypeOf(runx.Diagnostic{}), "Diagnostic"},
	{reflect.TypeOf(Snapshot{}), "FleetSnapshot"},
	{reflect.TypeOf(Counts{}), "FleetCounts"},
	{reflect.TypeOf(Project{}), "FleetProject"},
	{reflect.TypeOf(Session{}), "FleetSession"},
	{reflect.TypeOf(CodexRow{}), "CodexRow"},
	{reflect.TypeOf(Revive{}), "FleetRevive"},
	{reflect.TypeOf(ReviveSession{}), "ReviveSession"},
	{reflect.TypeOf(Ledger{}), "Ledger"},
	{reflect.TypeOf(Owner{}), "LedgerOwner"},
	{reflect.TypeOf(Job{}), "LedgerJob"},
	{reflect.TypeOf(Event{}), "LedgerEvent"},
}

// tsUnions are the string enums, rendered as literal unions.
var tsUnions = []struct {
	goType reflect.Type
	name   string
	values []string
}{
	{reflect.TypeOf(State("")), "FleetState", []string{string(StateWaiting), string(StateBusy), string(StateIdle), string(StateShell), string(StateDead), string(StateEnded), string(StateUnknown)}},
	{reflect.TypeOf(Liveness("")), "Liveness", []string{string(LivenessAlive), string(LivenessGone), string(LivenessForeign), string(LivenessRecycled), string(LivenessUnknown)}},
	{reflect.TypeOf(ReviveSource("")), "ReviveSource", []string{string(ReviveRegistry), string(ReviveLedger)}},
	{reflect.TypeOf(JobKind("")), "JobKind", kindStrings()},
	{reflect.TypeOf(JobStatus("")), "JobStatus", statusStrings()},
}

var timeType = reflect.TypeOf(time.Time{})

// TypeScript renders the JSON contracts of `fleet --json`, `fleet revive
// --json` and `fleet ledger …` as one .d.ts module. A mod keeps a copy at
// types/fleet.gen.d.ts; the drift test holds every copy equal to this.
func TypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by `vybava fleet schema --ts`. DO NOT EDIT.\n")
	b.WriteString("// Contracts of the fleet applet's --json output; docs/fleet.md.\n\n")
	fmt.Fprintf(&b, "export interface Envelope<T> {\n  v: %d\n  ok: boolean\n  verb: string\n  data?: T\n  diagnostics: Diagnostic[]\n  next: string[]\n}\n", runx.EnvelopeVersion)
	for _, union := range tsUnions {
		quoted := make([]string, len(union.values))
		for i, value := range union.values {
			quoted[i] = fmt.Sprintf("%q", value)
		}
		fmt.Fprintf(&b, "\nexport type %s = %s\n", union.name, strings.Join(quoted, " | "))
	}
	for _, named := range tsNamed {
		fmt.Fprintf(&b, "\nexport interface %s {\n", named.name)
		for i := 0; i < named.goType.NumField(); i++ {
			field := named.goType.Field(i)
			name, optional, skip := jsonField(field)
			if skip {
				continue
			}
			fieldType := field.Type
			if fieldType.Kind() == reflect.Pointer {
				optional = true
				fieldType = fieldType.Elem()
			}
			mark := ""
			if optional {
				mark = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s\n", name, mark, tsType(fieldType))
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func jsonField(field reflect.StructField) (name string, optional, skip bool) {
	if !field.IsExported() {
		return "", false, true
	}
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, true
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		name = field.Name
	}
	for _, option := range parts[1:] {
		if option == "omitempty" {
			optional = true
		}
	}
	return name, optional, false
}

func tsType(t reflect.Type) string {
	if t == timeType {
		return "string"
	}
	for _, union := range tsUnions {
		if t == union.goType {
			return union.name
		}
	}
	for _, named := range tsNamed {
		if t == named.goType {
			return named.name
		}
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return tsType(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsType(t.Elem()) + ">"
	case reflect.Pointer:
		return tsType(t.Elem())
	}
	panic(fmt.Sprintf("fleet: no TypeScript rendering for %s — list it in tsNamed or tsUnions", t))
}

func kindStrings() []string {
	out := make([]string, len(jobKinds))
	for i, kind := range jobKinds {
		out[i] = string(kind)
	}
	return out
}

func statusStrings() []string {
	out := make([]string, len(jobStatuses))
	for i, status := range jobStatuses {
		out[i] = string(status)
	}
	return out
}
