// Code generated by `vybava fleet schema --ts`. DO NOT EDIT.
// Contracts of the fleet applet's --json output; docs/fleet.md.

export interface Envelope<T> {
  v: 3
  ok: boolean
  verb: string
  data?: T
  diagnostics: Diagnostic[]
  next: string[]
}

export type FleetState = "waiting" | "busy" | "idle" | "shell" | "dead" | "ended" | "unknown"

export type Liveness = "alive" | "gone" | "foreign" | "recycled" | "unknown"

export type ReviveSource = "registry" | "ledger"

export type JobKind = "workflow" | "shell" | "monitor" | "agent" | "limit-wait" | "park"

export type JobStatus = "started" | "completed" | "failed" | "killed" | "stopped"

export interface Diagnostic {
  code: string
  severity: string
  detail: string
  fix?: string
}

export interface FleetSnapshot {
  generatedAt: string
  registry: string
  counts: FleetCounts
  projects: FleetProject[]
  sessions: FleetSession[]
  codex: CodexRow[]
}

export interface FleetCounts {
  total: number
  waiting: number
  busy: number
  idle: number
  shell: number
  dead: number
  ended: number
  unknown: number
}

export interface FleetProject {
  project: string
  root?: string
  counts: FleetCounts
}

export interface FleetSession {
  sessionId: string
  pid: number
  name?: string
  project: string
  root?: string
  worktree?: string
  cwd: string
  status: string
  state: FleetState
  waitingFor?: string
  statusSince: string
  ageSeconds: number
  startedAt?: string
  version?: string
  kind?: string
  entrypoint?: string
  liveness: Liveness
  openJobs: number
  resume: string
}

export interface CodexRow {
  pid: number
  tty?: string
  threadId: string
  name?: string
  project: string
  root?: string
  cwd: string
  branch?: string
  startedAt?: string
  lastCallAt?: string
  calls: number
}

export interface FleetRevive {
  generatedAt: string
  sessions: ReviveSession[]
}

export interface ReviveSession {
  sessionId: string
  name?: string
  project: string
  root?: string
  worktree?: string
  cwd?: string
  status?: string
  since: string
  source: ReviveSource
  liveness: Liveness
  resume: string
  openJobs: LedgerJob[]
}

export interface Ledger {
  version: number
  sessionId: string
  cwd?: string
  owner?: LedgerOwner
  updatedAt: string
  jobs: LedgerJob[]
}

export interface LedgerOwner {
  pid: number
  procStart: string
  pidDomain?: string
}

export interface LedgerJob {
  kind: JobKind
  id: string
  status: JobStatus
  runId?: string
  scriptPath?: string
  description?: string
  digest?: string
  until?: string
  startedAt: string
  endedAt?: string
  updatedAt: string
}

export interface LedgerEvent {
  kind: JobKind
  id: string
  status: JobStatus
  at?: string
  runId?: string
  scriptPath?: string
  description?: string
  command?: string
  until?: string
  cwd?: string
}

export interface FleetSummary {
  generatedAt: string
  counts: FleetCounts
  waiting: FleetSummarySession[]
}

export interface FleetSummarySession {
  sessionId: string
  name?: string
  project: string
  waitingFor?: string
  ageSeconds: number
}
