// Generated by `vybava config init` — do not edit. `vybava config check` fails
// on drift; `vybava config init --force` rewrites it after a vybava upgrade.

/** Key style of a locale catalog. */
export type CatalogStyle =
  /** The key IS the English source text: t('Save'). An `en` file, if present, maps key → key. */
  | 'english-as-key'
  /** Nested JSON addressed by dotted path: meta.title. */
  | 'path';

export interface ScanConfig {
  /** Directories scanned for translation calls, relative to the repo root. */
  roots: string[];
  /**
   * Call shapes whose first literal argument is a key (default: t). A bare
   * name (`t`) matches `t('…')` only with nothing dotted before it; the method
   * form (`*.T`) matches `.T('…')` on any receiver — `l.T("Sites")`,
   * `i18n.FromContext(ctx).N("{{count}} items", n)`. One list scans TS and Go
   * into the same catalog: `['t', '*.T', '*.N']` with `.go` in `extensions`.
   */
  call?: string | string[];
  /** File extensions to scan (default: .ts .tsx .js .jsx). */
  extensions?: string[];
}

/**
 * Source literals an english-as-key catalog's keys copy (API error sentences
 * a client translates). `lok mv` / `lok sub --keys` refuse a rename of such a
 * key (MIRROR_SOURCE) unless `--with-mirrors` rewrites the literal too.
 */
export interface MirrorConfig {
  /** Directories holding the source literals, relative to the repo root (spec files are listed, never rewritten). */
  roots: string[];
  /**
   * The catalog ships inside a store app binary while the mirror source
   * deploys on its own: a store-live app keeps the old keys after the source
   * text changes, so every rename warns (retire in three steps).
   */
  bundledInStoreApp?: boolean;
}

export interface CatalogConfig {
  style: CatalogStyle;
  /** File pattern with a `{locale}` placeholder, relative to the repo root. */
  files: string;
  /** Every locale the catalog ships. */
  locales: string[];
  /** Locales every key must carry (default: all). Others are tracked by `lok missing`. */
  required?: string[];
  /** Plural suffixes that make a key a variant of its base (default: _zero _one _two _few _many _other). */
  plurals?: string[];
  /** Shell command run after any write, from the repo root (e.g. a type generator). */
  afterWrite?: string;
  /** Regexes for keys excused from the english-as-key invariant (structured keys like `_help$` whose en value is prose). */
  exempt?: string[];
  /** Source scan for english-as-key catalogs. */
  scan?: ScanConfig;
  /** Source literals the keys mirror (english-as-key only); see MirrorConfig. */
  mirrors?: MirrorConfig;
}

export interface LokConfig {
  catalogs: Record<string, CatalogConfig>;
}

export interface MergeGenerated {
  /** Repository-relative globs (** spans directories) of files a command regenerates. */
  paths: string[];
  /** Shell command run once from the repo root after a merge touched any of them. */
  regen: string;
}

export interface MergeMigrations {
  /** Migration directory, relative to the repo root. */
  dir: string;
  /** `<ts>-<Name>.ts` files holding `class <Name><ts>` and `name = '<Name><ts>'`. */
  style: 'typeorm';
  /** Renumbered migrations start at the first multiple of step above the base's newest (default 1e8). */
  step?: number;
  /** The repo's own migration guard, run after a renumber. */
  check?: string;
}

/** merge-assist: what a merge settles without a session (catalogs come from lok). */
export interface MergeConfig {
  generated?: MergeGenerated[];
  migrations?: MergeMigrations[];
}

/** One repository that ships in the release. */
export interface ReadinessRepo {
  /** Ref prefix in inventories and lane bodies: `app#123`, `app@abc1234`. */
  id: string;
  /** Relative to the directory holding this config. */
  path: string;
  /** owner/name on GitHub. */
  github: string;
  /** Default origin. */
  remote?: string;
  /** What production runs: the newest tag matching `tag` reachable from `integration` (minus `exclude`), or a branch. */
  production: { tag: string; exclude?: string } | { branch: string };
  /** The branch lanes merge into. */
  integration: string;
  /** Creates a lane checkout of this repo; {slug} {path} (its resolved main clone). Required for every repo but the first. */
  worktree?: string;
}

export interface ReadinessDevice {
  id: string;
  platform: 'ios' | 'android' | 'web';
  framework: 'appium' | 'playwright';
  host: 'mac' | 'devbox' | 'ci';
  /** Human name on boards: 'iPhone 17 Pro', 'Pixel 7 · API 35', 'Desktop Chrome 1440×810'. */
  name: string;
  /** Screenshot width a board card must show for this device. */
  width?: number;
  /** Builds the app a release run installs; {commit} {apiUrl} {out} {worktree}. */
  build?: string;
  /** Runs specs; {specs} {apiUrl} {app} {runDir} {udid} {worktree} {grep} {port} {driverPort} (runner-assigned ports). */
  run: string;
}

/** readiness: what a release-readiness run needs to know about this project. Command strings take {token} placeholders; `readiness check` rejects unknown ones. */
export interface ReadinessConfig {
  vitrinka: { workspace: string; project: string };
  /** ~/Exports/<exports>/release-readiness-<date> is the default run directory. */
  exports?: string;
  repos: ReadinessRepo[];
  lane: {
    /** Creates the lane checkout; {slug}. */
    worktree: string;
    /** The lane stack's {ws} name; {slug}. */
    workspace?: string;
    /** Lane stack verbs; {ws} {slug}. url takes {ws} {app}; checks run once after up. */
    devEnv: { up: string; hold: string; park: string; url?: string; checks?: string[] };
    /** Wraps every heavy job (suite, build, browser batch); must contain {cmd}. */
    heavy: string;
  };
  /** Suites lanes extend and run through lane.heavy; {pattern}. */
  tests?: { name: string; framework?: string; cmd: string }[];
  devices: {
    /** 'device-runner' = one orchestrator-owned agent owns every simulator and emulator. */
    runner: 'lane' | 'device-runner';
    build: 'release' | 'dev-client';
    /** Most devices driven at once (default 2); keep it ≤ guards.simCap. */
    concurrent?: number;
    /** Every run resets the lane's shared test data: never two runs on one lane at once. */
    oneRunPerLane?: boolean;
    matrix: ReadinessDevice[];
    /** Multi-actor specs run with the roles on different platforms; run takes {spec} {apiUrl} {runDir} {worktree} {iosApp} {androidApp} {port}, and per role {<role>} (its platform) and {<role>Udid}. */
    realtime?: { specs: string[]; roles: string[]; directions: 'both' | 'one'; run: string };
  };
  /** order lists repo ids, first to merge first. */
  merge: { command: string; order?: string[] };
  /** checks: read-only release gates on the merged integration branch; handoff: the ship command the run never runs. */
  final?: { checks?: string[]; handoff?: string };
  /** Project traps rendered verbatim into lane-rules.md. */
  rules?: string[];
  /** Shared prerequisites known to be missing; phase 3 builds them first. */
  plumbing?: string[];
}

export interface VybavaConfig {
  lok?: LokConfig;
  merge?: MergeConfig;
  readiness?: ReadinessConfig;
  guards?: {
    /** Repository-relative globs; ** spans directories. Query these files with rg. */
    noRead?: string[];
    /** Maximum text lines per read (default: 200). */
    maxDumpLines?: number;
    /** Commands requiring capped output. Omit for built-ins; [] disables this rule. */
    unboundedCommands?: string[];
    /** Extra trees whose scripts may open and delete a webdriverio session (trailing slash = subtree, else a glob; matched at any depth). Defaults: appium/support/, appium/adhoc/lib/, appium/specs/, every .spec.ts under appium/, e2e/. */
    appiumSessionDirs?: string[];
    /** Most workers a playwright/vitest/jest run may ask for on this machine (machine:test-worker-cap); at least 1, default 2. Heavier runs go to the Devbox or set CLAUDE_GUARDS_ALLOW_TEST_WORKERS=1. */
    testWorkerCap?: number;
    /** RE2 patterns over one local command segment; a match must run through `devbox run -- '<cmd>'` (machine:devbox-only). Escape: CLAUDE_GUARDS_ALLOW_LOCAL_STACK=1. */
    devboxOnly?: string[];
    /** RE2 patterns matched like devboxOnly, refused only when the checkout the command runs in (after its own cd / bun --cwd) has a Devbox workspace in the local registry ($DEVBOX_WORKSPACES_DIR or ~/.devbox/workspaces, parked or not) - machine:devbox-workspace; elsewhere the command may run here. Escape: CLAUDE_GUARDS_ALLOW_LOCAL_STACK=1. */
    devboxWhenWorkspace?: string[];
    /** Most booted simulators before a boot is refused (machine:sim-cap); at least 1, default 2. */
    simCap?: number;
    /** Most Metro/next/API dev servers before a start is refused (machine:dev-server-cap); at least 1, default 3. */
    devServerCap?: number;
  };
}

/** Identity with types — the config file's default export. */
export const defineConfig = <T extends VybavaConfig>(config: T): T => config;

/** A flat catalog whose keys are the English source text. */
export const englishAsKey = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'english-as-key', files, locales, ...rest });

/** A nested catalog addressed by dotted path. */
export const pathKeys = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'path', files, locales, ...rest });
