// Generated by `vybava config init` — do not edit. `vybava config check` fails
// on drift; `vybava config init --force` rewrites it after a vybava upgrade.

/** Key style of a locale catalog. */
export type CatalogStyle =
  /** The key IS the English source text: t('Save'). An `en` file, if present, maps key → key. */
  | 'english-as-key'
  /** Nested JSON addressed by dotted path: meta.title. */
  | 'path';

export interface ScanConfig {
  /** Directories scanned for translation calls, relative to the repo root. */
  roots: string[];
  /**
   * Call shapes whose first literal argument is a key (default: t). A bare
   * name (`t`) matches `t('…')` only with nothing dotted before it; the method
   * form (`*.T`) matches `.T('…')` on any receiver — `l.T("Sites")`,
   * `i18n.FromContext(ctx).N("{{count}} items", n)`. One list scans TS and Go
   * into the same catalog: `['t', '*.T', '*.N']` with `.go` in `extensions`.
   */
  call?: string | string[];
  /** File extensions to scan (default: .ts .tsx .js .jsx). */
  extensions?: string[];
}

export interface CatalogConfig {
  style: CatalogStyle;
  /** File pattern with a `{locale}` placeholder, relative to the repo root. */
  files: string;
  /** Every locale the catalog ships. */
  locales: string[];
  /** Locales every key must carry (default: all). Others are tracked by `lok missing`. */
  required?: string[];
  /** Plural suffixes that make a key a variant of its base (default: _zero _one _two _few _many _other). */
  plurals?: string[];
  /** Shell command run after any write, from the repo root (e.g. a type generator). */
  afterWrite?: string;
  /** Regexes for keys excused from the english-as-key invariant (structured keys like `_help$` whose en value is prose). */
  exempt?: string[];
  /** Source scan for english-as-key catalogs. */
  scan?: ScanConfig;
}

export interface LokConfig {
  catalogs: Record<string, CatalogConfig>;
}

export interface MergeGenerated {
  /** Repository-relative globs (** spans directories) of files a command regenerates. */
  paths: string[];
  /** Shell command run once from the repo root after a merge touched any of them. */
  regen: string;
}

export interface MergeMigrations {
  /** Migration directory, relative to the repo root. */
  dir: string;
  /** `<ts>-<Name>.ts` files holding `class <Name><ts>` and `name = '<Name><ts>'`. */
  style: 'typeorm';
  /** Renumbered migrations start at the first multiple of step above the base's newest (default 1e8). */
  step?: number;
  /** The repo's own migration guard, run after a renumber. */
  check?: string;
}

/** merge-assist: what a merge settles without a session (catalogs come from lok). */
export interface MergeConfig {
  generated?: MergeGenerated[];
  migrations?: MergeMigrations[];
}

export interface VybavaConfig {
  lok?: LokConfig;
  merge?: MergeConfig;
  guards?: {
    /** Repository-relative globs; ** spans directories. Query these files with rg. */
    noRead?: string[];
    /** Maximum text lines per read (default: 200). */
    maxDumpLines?: number;
    /** Commands requiring capped output. Omit for built-ins; [] disables this rule. */
    unboundedCommands?: string[];
    /** Extra trees whose scripts may open and delete a webdriverio session (trailing slash = subtree, else a glob; matched at any depth). Defaults: appium/support/, appium/adhoc/lib/, appium/specs/, every .spec.ts under appium/, e2e/. */
    appiumSessionDirs?: string[];
    /** Most workers a playwright/vitest/jest run may ask for on this machine (machine:test-worker-cap); at least 1, default 2. Heavier runs go to the Devbox or set CLAUDE_GUARDS_ALLOW_TEST_WORKERS=1. */
    testWorkerCap?: number;
    /** RE2 patterns over one local command segment; a match must run through `devbox run -- '<cmd>'` (machine:devbox-only). Escape: CLAUDE_GUARDS_ALLOW_LOCAL_STACK=1. */
    devboxOnly?: string[];
    /** Most booted simulators before a boot is refused (machine:sim-cap); at least 1, default 2. */
    simCap?: number;
    /** Most Metro/next/API dev servers before a start is refused (machine:dev-server-cap); at least 1, default 3. */
    devServerCap?: number;
  };
}

/** Identity with types — the config file's default export. */
export const defineConfig = <T extends VybavaConfig>(config: T): T => config;

/** A flat catalog whose keys are the English source text. */
export const englishAsKey = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'english-as-key', files, locales, ...rest });

/** A nested catalog addressed by dotted path. */
export const pathKeys = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'path', files, locales, ...rest });
