// Generated by `vybava config init` - do not edit. `vybava config check` fails
// on drift; `vybava config init --force` rewrites it after a vybava upgrade.

/** Key style of a locale catalog. */
export type CatalogStyle =
  /** The key IS the English source text: t('Save'). An `en` file, if present, maps key → key. */
  | 'english-as-key'
  /** Nested JSON addressed by dotted path: meta.title. */
  | 'path';

export interface ScanConfig {
  /** Directories scanned for translation calls, relative to the repo root. */
  roots: string[];
  /**
   * Call shapes whose first literal argument is a key (default: t). A bare
   * name (`t`) matches `t('…')` only with nothing dotted before it; the method
   * form (`*.T`) matches `.T('…')` on any receiver: `l.T("Sites")`,
   * `i18n.FromContext(ctx).N("{{count}} items", n)`. One list scans TS and Go
   * into the same catalog: `['t', '*.T', '*.N']` with `.go` in `extensions`.
   */
  call?: string | string[];
  /** File extensions to scan (default: .ts .tsx .js .jsx). */
  extensions?: string[];
}

/**
 * Source literals an english-as-key catalog's keys copy (API error sentences
 * a client translates). `lok mv` / `lok sub --keys` refuse a rename of such a
 * key (MIRROR_SOURCE) unless `--with-mirrors` rewrites the literal too.
 */
export interface MirrorConfig {
  /** Directories holding the source literals, relative to the repo root (spec files are listed, never rewritten). */
  roots: string[];
  /**
   * The catalog ships inside a store app binary while the mirror source
   * deploys on its own: a store-live app keeps the old keys after the source
   * text changes, so every rename warns (retire in three steps).
   */
  bundledInStoreApp?: boolean;
}

export interface CatalogConfig {
  style: CatalogStyle;
  /** File pattern with a `{locale}` placeholder, relative to the repo root. */
  files: string;
  /** Every locale the catalog ships. */
  locales: string[];
  /** Locales every key must carry (default: all). Others are tracked by `lok missing`. */
  required?: string[];
  /** Plural suffixes that make a key a variant of its base (default: _zero _one _two _few _many _other). */
  plurals?: string[];
  /** Shell command run after any write, from the repo root (e.g. a type generator). */
  afterWrite?: string;
  /** Regexes for keys excused from the english-as-key invariant (structured keys like `_help$` whose en value is prose). */
  exempt?: string[];
  /** Source scan for english-as-key catalogs. */
  scan?: ScanConfig;
  /** Source literals the keys mirror (english-as-key only); see MirrorConfig. */
  mirrors?: MirrorConfig;
}

export interface LokConfig {
  catalogs: Record<string, CatalogConfig>;
}

export interface MergeGenerated {
  /** Repository-relative globs (** spans directories) of files a command regenerates. */
  paths: string[];
  /** Shell command run once from the repo root after a merge touched any of them. */
  regen: string;
}

export interface MergeMigrations {
  /** Migration directory, relative to the repo root. */
  dir: string;
  /** `<ts>-<Name>.ts` files holding `class <Name><ts>` and `name = '<Name><ts>'`. */
  style: 'typeorm';
  /** Renumbered migrations start at the first multiple of step above the base's newest (default 1e8). */
  step?: number;
  /** The repo's own migration guard, run after a renumber. */
  check?: string;
}

/** merge-assist: what a merge settles without a session (catalogs come from lok). */
export interface MergeConfig {
  generated?: MergeGenerated[];
  migrations?: MergeMigrations[];
}

/** One repository that ships in the release. */
export interface ReadinessRepo {
  /** Ref prefix in inventories and lane bodies: `app#123`, `app@abc1234`. */
  id: string;
  /** Relative to the directory holding this config. */
  path: string;
  /** owner/name on GitHub. */
  github: string;
  /** Default origin. */
  remote?: string;
  /** What production runs: the newest tag matching `tag` reachable from `integration` (minus `exclude`), or a branch. */
  production: { tag: string; exclude?: string } | { branch: string };
  /** The branch lanes merge into. */
  integration: string;
  /** Creates a lane checkout of this repo; {slug} {path} (its resolved main clone). Required for every repo but the first. */
  worktree?: string;
}

export interface ReadinessDevice {
  id: string;
  platform: 'ios' | 'android' | 'web';
  framework: 'appium' | 'playwright';
  host: 'mac' | 'devbox' | 'ci';
  /** Human name on boards: 'iPhone 17 Pro', 'Pixel 7 · API 35', 'Desktop Chrome 1440×810'. */
  name: string;
  /** Screenshot width a board card must show for this device. */
  width?: number;
  /** Builds the app a release run installs; {commit} {apiUrl} {out} {worktree}. */
  build?: string;
  /** Runs specs; {specs} {apiUrl} {app} {runDir} {udid} {worktree} {grep} {port} {driverPort} (runner-assigned ports). */
  run: string;
}

/** readiness: what a release-readiness run needs to know about this project. Command strings take {token} placeholders; `readiness check` rejects unknown ones. */
export interface ReadinessConfig {
  vitrinka: { workspace: string; project: string };
  /** ~/Exports/<exports>/release-readiness-<date> is the default run directory. */
  exports?: string;
  repos: ReadinessRepo[];
  lane: {
    /** Creates the lane checkout; {slug}. */
    worktree: string;
    /** The lane stack's {ws} name; {slug}. */
    workspace?: string;
    /** Lane stack verbs; {ws} {slug}. url takes {ws} {app}; checks run once after up. */
    devEnv: { up: string; hold: string; park: string; url?: string; checks?: string[] };
    /** Wraps every heavy job (suite, build, browser batch); must contain {cmd}. */
    heavy: string;
  };
  /** Suites lanes extend and run through lane.heavy; {pattern}. */
  tests?: { name: string; framework?: string; cmd: string }[];
  devices: {
    /** 'device-runner' = one orchestrator-owned agent owns every simulator and emulator. */
    runner: 'lane' | 'device-runner';
    build: 'release' | 'dev-client';
    /** Most devices driven at once (default 2); keep it ≤ guards.simCap. */
    concurrent?: number;
    /** Every run resets the lane's shared test data: never two runs on one lane at once. */
    oneRunPerLane?: boolean;
    matrix: ReadinessDevice[];
    /** Multi-actor specs run with the roles on different platforms; run takes {spec} {apiUrl} {runDir} {worktree} {iosApp} {androidApp} {port}, and per role {<role>} (its platform) and {<role>Udid}. */
    realtime?: { specs: string[]; roles: string[]; directions: 'both' | 'one'; run: string };
  };
  /** order lists repo ids, first to merge first. */
  merge: { command: string; order?: string[] };
  /** checks: read-only release gates on the merged integration branch; handoff: the ship command the run never runs. */
  final?: { checks?: string[]; handoff?: string };
  /** Project traps rendered verbatim into lane-rules.md. */
  rules?: string[];
  /** Shared prerequisites known to be missing; phase 3 builds them first. */
  plumbing?: string[];
}

/** One app the UI loop shoots. */
export interface UiLoopApp {
  baseUrl: string;
  /** Env var that overrides baseUrl wherever it is set; the capture machine's value wins last. */
  env?: string;
  /** Viewport ids (built-ins: phone, phone-320, phone-360, phone-landscape, tablet, laptop, desktop). */
  viewports: string[];
  themes: ('light' | 'dark')[];
}

/** A capture viewport (DPR 2); `mobile` = coarse pointer, touch UA, touch-target lint. */
export interface UiLoopViewport {
  width: number;
  height: number;
  mobile?: boolean;
  insets?: { top: number; right: number; bottom: number; left: number };
}

/** ui-loop: the UI polish loop's capture harness, passes, publish and scoreboard (docs/uiloop.md). */
export interface UiLoopConfig {
  /** Holds project.ts, screens/ and the synced vendor/ (repo-relative). */
  dir: string;
  /** Gitignored run root; one directory per pass (<out>/pass-<n>). */
  out: string;
  /** The rendered app map, drift-checked by `ui-loop check`. */
  appMap: string;
  /** The written design spec reviewers judge against. */
  spec?: string;
  /** How the repo runs Playwright: 'pnpm exec playwright test', 'bunx playwright test'. */
  runner: string;
  /** Runs a TypeScript file (check, app map): 'pnpm exec tsx', 'bun'. Default: bun in a bun repo, else 'npx --yes tsx'. */
  tsRunner?: string;
  /** Capture and publish order. */
  areas: string[];
  apps: Record<string, UiLoopApp>;
  /** Adds or overrides viewport ids. */
  viewports?: Record<string, UiLoopViewport>;
  lint?: {
    /** Spacing grid in px (default 4). */
    grid?: number;
    /** Minimum coarse-pointer target in px (default 44). */
    touchTarget?: number;
    /** Rule ids switched off. */
    off?: string[];
    /** The type ramp in px; the type-ramp rule runs only when set. */
    ramp?: number[];
    /**
     * Defect rule id → CSS selectors. A hit on an element that matches one, or
     * sits inside one, counts as info, not as a defect:
     * `{ grid: ['ui-button', '.ui-badge-small', '[role=menuitem]'] }`.
     */
    allow?: Record<string, string[]>;
  };
  vitrinka: { project: string; boardPrefix: string };
  publish?: {
    /** @deprecated Ignored: a pass publishes one vitrinka set per area. Delete it. */
    maxFiles?: number;
    /** @deprecated Ignored: a pass publishes one vitrinka set per area. Delete it. */
    maxBytes?: number;
    /** rsync source of the repo on the capture box, e.g. 'devops:ws/<workspace>/<app-dir>'; `publish --follow` appends /<out>/pass-<n>/. */
    from?: string;
  };
  /**
   * The application source as git pathspecs: only a change here stales a pass (`state`'s drift.app).
   * Default: the repo minus out, .vitrinka, dir, spec, appMap, every *.md and .claude/.
   */
  source?: string[];
  /** Directory prefixes holding shared primitives: `lanes --primitives`' default; a change under one makes a verify a full reshoot. */
  primitives?: string[];
}

/** One axis of the polish verb: what the pass polishes. */
export type PolishTarget = 'app' | 'ui' | 'api';

/** What a polish lane resolves to. */
export type PolishLaneKind = 'ios-sim' | 'ios-device' | 'android-device' | 'android-emulator' | 'browser' | 'server';

/** One device or URL a target is polished on (polish-kit lanes). */
export interface PolishLane {
  /** 'ios26', 'ios18', 'android'. */
  id: string;
  target: PolishTarget;
  kind: PolishLaneKind;
  /** iOS runtime version the lane needs, e.g. '18.6' or '26.5' (ios-sim); matched by prefix against `xcrun simctl list runtimes`. */
  runtime?: string;
  /** Simulator device type name, e.g. 'iPhone 17 Pro' (ios-sim / android-emulator AVD name). */
  deviceType?: string;
  /** Physical device: devicectl name/udid (ios-device) or adb serial (android-device); ios-sim: pin the one simulator (name/udid) of the type, else any shutdown sim of the type is taken. */
  device?: string;
  /** Android navigation modes the lane must be shot in (default: ['gesture']). */
  nav?: ('gesture' | '3button')[];
  /** Default both. */
  themes?: ('light' | 'dark')[];
  /** Content-size / font-scale steps to shoot besides default: iOS `xcrun simctl ui content_size` names, Android font_scale numbers as strings. */
  textSizes?: string[];
  /** e.g. 'cs'. */
  locale?: string;
  /** browser lane: base URL; server lane: health URL. With urlCommand: a path (starting with /) appended to the command's output, or an absolute URL used as is. */
  url?: string;
  /** Shell command (sh -c, from the repo root) whose first output line is the lane's base URL, for an app whose address is leased per run: 'devbox url <ws> api'. Exactly one of url / urlCommand for browser and server lanes. */
  urlCommand?: string;
}

/** One screen a chrome cell shoots (polish-kit shoot). */
export interface PolishScreen {
  id: string;
  title: string;
  target: 'app' | 'ui';
  /** app: a deep link the app opens (scheme URL); ui: a path under the lane url. */
  url: string;
  /** Wait after opening before the shot (default 1500). */
  settleMs?: number;
  /** Area name; a changed path holding it marks the screen touched. */
  area?: string;
}

/** polish-kit: the polish skill's deterministic layer (docs/polish-kit.md). Go twin: internal/polishkit/config.go; change both together. */
export interface PolishConfig {
  /** Repository-relative globs per target; a changed file maps to the first target (app, ui, api order) whose glob matches. */
  targets: Partial<Record<PolishTarget, string[]>>;
  /** Base ref for the diff (default: origin/main, falling back to the repo default branch). */
  base?: string;
  /** Gitignored run root (default '.polish'): <out>/pass-<n>/run.json and shots. */
  out?: string;
  lanes: PolishLane[];
  screens?: PolishScreen[];
}

/**
 * perflab: the project adapter of the physical-device perf lab (docs/perflab.md "Adapter").
 * Go twin: internal/perflab/config.go; change both together. Commands run with sh -c from the
 * repo root; {token} values are closed per field and checked by `perflab adapter check`.
 */
export interface PerflabConfig {
  app: {
    /** The Expo app, relative to the repo root ('apps/client'). */
    root: string;
    /** JS entry relative to root (default 'index.js'). */
    entry?: string;
    ios?: { scheme: string; bundleId: string; team?: string };
    android?: { package: string; activity?: string };
  };
  /** Build profiles: env prints KEY=VALUE lines; {platform} {profile} {apiOrigin} {deviceApiOrigin} {devicePort} {ws} {appRoot}. */
  profiles: Record<string, { env: string }>;
  /** Default `bunx @expo/fingerprint fingerprint:generate {appRoot} --platform {platform} --debug`; extraNativeInputs are '<file>#<json pointer>'. */
  fingerprint?: { cmd?: string; extraNativeInputs?: string[] };
  /** Project build recipes; each writes exactly one .app / .apk into {outDir}. */
  build?: { iosBundled?: string; android?: string };
  /** Prints the scenario rows as JSON: [{name, windowMs, platforms?, budget?, stepCycle?, stepGroups?}]. */
  scenarios: string;
  runner: {
    /** Runs the scenarios; {platform} {scenarios} {runDir} {timeoutMs} {variant} {udid} {serial} … */
    cmd: string;
    /** Env for the runner; values take the run tokens. */
    env?: Record<string, string>;
    /** Removed from the runner's environment. */
    unset?: string[];
    appiumHome?: string;
    appiumServerLog?: string;
  };
  api?: {
    /** The API workspace name; {branch} {branchSlug}. */
    ws?: string;
    /** Prints the host-side API origin; {ws}. */
    origin: string;
    /** DEVBOX_PARKED fix; {ws}. */
    hold?: string;
    /** Health path, e.g. '/api/v1/health/ready'. */
    health?: string;
    device?: {
      android?: { strategy: 'reverse'; devicePort: number };
      ios?: { strategy: 'bake'; origin?: string };
    };
  };
  hooks?: {
    /** Prints a sign-in deep link; {account} {route} {platform} {apiOrigin} {deviceApiOrigin} {ws}. */
    signInLink?: string;
    /** Resets the seeded world; {world} {scenario} {platform} {apiOrigin} {deviceApiOrigin} {ws}. */
    resetWorld?: string;
  };
  /** Run dir root; {date} {topic}; default '~/Exports/perflab/{date}-{topic}'. */
  out?: string;
  hazards?: { ambientGates?: string[]; visibilityHint?: string[]; exclude?: string[] };
}

export interface VybavaConfig {
  lok?: LokConfig;
  merge?: MergeConfig;
  readiness?: ReadinessConfig;
  uiLoop?: UiLoopConfig;
  polish?: PolishConfig;
  perflab?: PerflabConfig;
  guards?: {
    /** Repository-relative globs; ** spans directories. Query these files with rg. */
    noRead?: string[];
    /** Maximum text lines per read (default: 200). */
    maxDumpLines?: number;
    /** Commands requiring capped output. Omit for built-ins; [] disables this rule. */
    unboundedCommands?: string[];
    /** Extra trees whose scripts may open and delete a webdriverio session (trailing slash = subtree, else a glob; matched at any depth). Defaults: appium/support/, appium/adhoc/lib/, appium/specs/, every .spec.ts under appium/, e2e/. */
    appiumSessionDirs?: string[];
    /** Most workers a playwright/vitest/jest run may ask for on this machine (machine:test-worker-cap); at least 1, default 2. Heavier runs go to the Devbox or set CLAUDE_GUARDS_ALLOW_TEST_WORKERS=1. */
    testWorkerCap?: number;
    /** RE2 patterns over one local command segment; a match must run through `devbox run -- '<cmd>'` (machine:devbox-only). Escape: CLAUDE_GUARDS_ALLOW_LOCAL_STACK=1. */
    devboxOnly?: string[];
    /** RE2 patterns matched like devboxOnly, refused only when the checkout the command runs in (after its own cd / bun --cwd) has a Devbox workspace in the local registry ($DEVBOX_WORKSPACES_DIR or ~/.devbox/workspaces, parked or not) - machine:devbox-workspace; elsewhere the command may run here. Escape: CLAUDE_GUARDS_ALLOW_LOCAL_STACK=1. */
    devboxWhenWorkspace?: string[];
    /** Most booted simulators before a boot is refused (machine:sim-cap); at least 1, default 2. */
    simCap?: number;
    /** Most Metro/next/API dev servers before a start is refused (machine:dev-server-cap); at least 1, default 3. */
    devServerCap?: number;
  };
}

/** Identity with types: the config file's default export. */
export const defineConfig = <T extends VybavaConfig>(config: T): T => config;

/** A flat catalog whose keys are the English source text. */
export const englishAsKey = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'english-as-key', files, locales, ...rest });

/** A nested catalog addressed by dotted path. */
export const pathKeys = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'path', files, locales, ...rest });
